### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlanBatler** [atom/autocomplete-css#100]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-css](https://github.com/atom/autocomplete-css) package 0.16.1

### Stack Trace

Failed to activate the autocomplete-css package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/main.js:110:1)
    at Object.requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/main.js:31:1)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/main.js:107:1)
    at Object.consumeProvider_2_0 (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/main.js:86:1)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/service-hub.js:30:1)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:374:1
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:185:1)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-card.js:361:1)
```

### Commands

```
  7x -0:41.6.0 core:backspace (input.hidden-input)
     -0:39.7.0 core:delete (input.hidden-input)
     -0:37.3.0 editor:newline (input.hidden-input)
  2x -0:31.2.0 core:move-left (input.hidden-input)
     -0:30.7.0 core:move-up (input.hidden-input)
     -0:30.6.0 core:move-left (input.hidden-input)
     -0:30.5.0 core:move-up (input.hidden-input)
     -0:30.4.0 core:move-left (input.hidden-input)
     -0:30.3.0 core:move-up (input.hidden-input)
     -0:30.2.0 core:move-left (input.hidden-input)
     -0:29.9.0 core:move-right (input.hidden-input)
     -0:29.8.0 core:move-down (input.hidden-input)
     -0:29.6.0 core:move-right (input.hidden-input)
     -0:29.5.0 core:move-down (input.hidden-input)
     -0:29.4.0 core:move-right (input.hidden-input)
     -0:29.3.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-paths 1.0.5 
emmet 2.4.3 
```

**Comment by winstliu** [comment]
Tracking at atom/autocomplete-plus#851.
