### ISSUE TITLE
Failed to activate the autocomplete-css package

### ISSUE THREAD

**Issue by zhangtanlin** [atom/autocomplete-css#95]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-css](https://github.com/atom/autocomplete-css) package 0.16.1

### Stack Trace

Failed to activate the autocomplete-css package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (D:/wode/atom/Atom x64/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (D:/wode/atom/Atom x64/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at requireAutocompleteManagerAsync (D:/wode/atom/Atom x64/resources/app/node_modules/autocomplete-plus/lib/main.js:110:1)
    at Object.requireAutocompleteManagerAsync (D:/wode/atom/Atom x64/resources/app/node_modules/autocomplete-plus/lib/main.js:31:1)
    at Object.consumeProvider (D:/wode/atom/Atom x64/resources/app/node_modules/autocomplete-plus/lib/main.js:107:1)
    at Object.consumeProvider_2_0 (D:/wode/atom/Atom x64/resources/app/node_modules/autocomplete-plus/lib/main.js:86:1)
    at Provider.module.exports.Provider.provide (D:/wode/atom/Atom x64/resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.provide (D:/wode/atom/Atom x64/resources/app/node_modules/service-hub/lib/service-hub.js:30:1)
    at Package.module.exports.Package.activateServices (D:/wode/atom/Atom x64/resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (D:/wode/atom/Atom x64/resources/app/src/package.js:256:1)
    at D:/wode/atom/Atom x64/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (D:/wode/atom/Atom x64/resources/app/src/package.js:99:1)
    at D:/wode/atom/Atom x64/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (D:/wode/atom/Atom x64/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (D:/wode/atom/Atom x64/resources/app/src/package-manager.js:642:1)
    at D:/wode/atom/Atom x64/resources/app/src/package-manager.js:374:1
    at D:/wode/atom/Atom x64/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (D:/wode/atom/Atom x64/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (D:/wode/atom/Atom x64/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (D:/wode/atom/Atom x64/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (D:/wode/atom/Atom x64/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (D:/wode/atom/Atom x64/resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (D:/wode/atom/Atom x64/resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (D:/wode/atom/Atom x64/resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (D:/wode/atom/Atom x64/resources/app/src/package-manager.js:185:1)
    at HTMLButtonElement.enablementButtonClickHandler (D:/wode/atom/Atom x64/resources/app/node_modules/settings-view/lib/package-card.js:361:1)
```

### Commands

```
     -9:11.6.0 package-generator:generate-package (div.package-detail.panels-item)
     -9:08.5.0 editor:consolidate-selections (input.hidden-input)
     -9:08.5.0 core:cancel (input.hidden-input)
     -8:46.7.0 command-palette:toggle (div.package-detail.panels-item)
     -8:34.5.0 core:confirm (input.hidden-input)
     -3:21.8.0 tabs:split-right (div.title.icon.icon-tools)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
bottom-dock 0.4.4 
emmet 2.4.3 
gulp-manager 0.2.19 
open-in-browsers 0.0.19 
sync-settings 0.8.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a couple of things for us?

* what were you doing at the time of the error?
* is the error is reproducible?

**Comment by rsese** [comment]
Going to go ahead and close this in favor of https://github.com/atom/autocomplete-plus/issues/851.    If you're able to share steps to reproduce @zhangtanlin, please let us know in the issue :v:

**Comment by ishang1993** [comment]
![screen shot 2017-07-20 at 6 49 15 pm](https://user-images.githubusercontent.com/26818921/28419325-346dcb60-6d7c-11e7-8da7-cda8a8eff908.png)

Autocomplete failed to enable. I disabled it and tried to enable it.

**Comment by rsese** [comment]
As mentioned [above](https://github.com/atom/autocomplete-css/issues/95#issuecomment-305339900) @ishang1993, this issue is tagged as a duplicate of https://github.com/atom/autocomplete-plus/issues/851 so you can subscribe there for updates if you'd like.
